version: '3'

services:

  auth-client:
    image: trg_app/auth-client:0.0.0.RELEASE
    build:
      dockerfile: ./apps/auth-client
    ports:
      - 3000:3000
    networks:
      - trg_network

  auth-server:
    image: trg_app/auth-server:0.0.0.RELEASE
    build:
      dockerfile: ./apps/auth-server
    ports:
      - 4000:4000
    networks:
      - trg_network

  dashboard-client:
    image: trg_app/dashboard-client:0.0.0.RELEASE
    build:
      dockerfile: ./apps/dashboard-client
    ports:
      - 3001:3001
    networks:
      - trg_network
      
  dashboard-server:
    image: trg_app/dashboard-server:0.0.0.RELEASE
    build:
      dockerfile: ./apps/dashboard-server
    ports:
      - 4001:4001
    networks:
      - trg_network

networks:
  trg_network:
    driver: bridge
